### ISSUE TITLE
Create string templates

### ISSUE THREAD

**Issue by dgershman** [bmlt-enabled/list-locations-bmlt#6]
I would like to be able to use some magic variables to create a specific view of the of the data.  For example:

`#city#, #state# (#county#)`

This would output for example

Willow Spring, NC (Johnston)

It's ok if they are the BMLT named fields as well.  I think other valuable fields could be other locational related views.

**Comment by pjaudiomv** [comment]
Just seeing this, that is a great idea. I will look into this.

**Comment by pjaudiomv** [comment]
This has been completed and is in 2.3.0 using BMLT fields.
`#location_municipality#, #location_province# (#location_sub_province#)`
there is one special magic var `#br#` that replace any occurrence with a breakrule tag `<br>`
